{
 "title": "监控大屏",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "总主机数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=~\"node_exporter|windows_exporter\"})"
    }
   ]
  },
  {
   "title": "正常主机数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=~\"node_exporter|windows_exporter\"}==1)"
    }
   ]
  },
  {
   "title": "异常主机数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=~\"node_exporter|windows_exporter\"}!=1)"
    }
   ]
  },
  {
   "title": "linux主机数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "windows主机数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"windows_exporter\"})"
    }
   ]
  },
  {
   "title": "VPC总入向带宽",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cni.*|dummy.*|kube-ipvs.*'}[5m])*8) + sum(irate(windows_net_bytes_received_total{nic!~'isatap.*|VPN.*'}[5m])*8)",
     "legendFormat": "VPC总入向带宽"
    }
   ]
  },
  {
   "title": "VPC出向总带宽",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cni.*|dummy.*|kube-ipvs.*'}[5m])*8) + sum(irate(windows_net_bytes_sent_total{nic!~'isatap.*|VPN.*'}[5m])*8)",
     "legendFormat": "VPC出向总带宽"
    }
   ]
  },
  {
   "title": "主机运行情况",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "0-（down）/1-（up）" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"node_exporter|windows_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "网络入向流量",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cni.*|dummy.*|kube-ipvs.*'}[5m])*8",
     "legendFormat": "{{instance}}-{{device}}"
    },
    {
     "expr": "irate(windows_net_bytes_received_total{nic!~'isatap.*|VPN.*'}[5m])*8",
     "legendFormat": "{{instance}}-{{nic}}"
    }
   ]
  },
  {
   "title": "网络出向流量",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cni.*|dummy.*|kube-ipvs.*'}[5m])*8",
     "legendFormat": "{{instance}}-{{device}}"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{nic!~'isatap.*|VPN.*'}[5m])*8",
     "legendFormat": "{{instance}}-{{nic}}"
    }
   ]
  }
 ]
}